# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.238.0/containers/go/.devcontainer/base.Dockerfile

# [Choice] Go version (use -bullseye variants on local arm64/Apple Silicon): 1, 1.16, 1.17, 1-bullseye, 1.16-bullseye, 1.17-bullseye, 1-buster, 1.16-buster, 1.17-buster
ARG VARIANT="1.20-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/go:0-${VARIANT}

# [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
ARG NODE_VERSION="none"
RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment the next lines to use go get to install anything else you need
# USER vscode
# RUN go get -x <your-dependency-or-tool>
# RUN go install golang.org/x/tools/cmd/goimports@latest && \
#     go install github.com/fzipp/gocyclo/cmd/gocyclo@latest && \
#     go install github.com/go-critic/go-critic/cmd/gocritic@latest && \
#     go install github.com/swaggo/swag/cmd/swag@latest && \
#     go install github.com/cosmtrek/air@latest && \
#     go install github.com/securego/gosec/v2/cmd/gosec@latest && \
#     go install mvdan.cc/gofumpt@latest && \
#     go install golang.org/x/tools/cmd/goimports@latest && \
#     go install sourcegraph.com/sqs/goreturns@latest && \
#     go install golang.org/x/lint/golint@latest && \
#     go install github.com/mattn/entgen@latest && \
#     go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest && \
#     go install mvdan.cc/gofumpt@latest && \
#     go install github.com/daixiang0/gci@latest

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
WORKDIR /workspaces
